name: 'Build Docker Image'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        type: string
        default: 'v5-build'
  schedule:
    - cron: '0 12 1 * *'
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "patches/**"
      - "root/**"
      - "Dockerfile"
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/build.yml"
      - "patches/**"
      - "root/**"
      - "Dockerfile"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ inputs.branch || 'v5-build' }}
  cancel-in-progress: true

env:
  FRAMEWORK: net10.0

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.head.repo.fork }}
    outputs:
      framework: ${{ steps.variables.outputs.framework }}
      branch: ${{ steps.variables.outputs.branch }}
      build_branch: ${{ steps.variables.outputs.build_branch }}
      tag_branch: ${{ steps.variables.outputs.tag_branch }}
      version: ${{ steps.ext_release.outputs.version }}
      semantic_version: ${{ steps.ext_release.outputs.semantic_version }}
    steps:
      - name: Setup variables
        id: variables
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
          BUILD_BRANCH: ${{ inputs.branch || 'v5-build' }}
        run: |
          BRANCH=${BRANCH_NAME,,}

          echo "framework=${FRAMEWORK}" >> "$GITHUB_OUTPUT"
          echo "branch=${BRANCH//\//-}" >> "$GITHUB_OUTPUT"
          echo "build_branch=${BUILD_BRANCH}" >> $GITHUB_OUTPUT
          echo "tag_branch=${BUILD_BRANCH,,}" >> $GITHUB_OUTPUT

      - name: Retrieving external version
        id: ext_release
        run: |
          EXT_RELEASE=$(curl -sL "https://services.sonarr.tv/v1/releases" | jq -r 'first(.[] | select(.branch=="develop") | .version)')
          if [ -z "${EXT_RELEASE}" ] || [ "${EXT_RELEASE}" == "null" ]; then
            echo "**** Can't retrieve external version, exiting ****"
            echo "Can't retrieve external version, exiting" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
          EXT_RELEASE=$(echo ${EXT_RELEASE} | sed 's/[~,%@+;:/]//g')
          echo "**** External version: ${EXT_RELEASE} ****"
          echo "External version: ${EXT_RELEASE}" >> $GITHUB_STEP_SUMMARY
          echo "version=${EXT_RELEASE}" >> "$GITHUB_OUTPUT"
          if [[ "${EXT_RELEASE}" =~ ^([0-9]+\.[0-9]+\.[0-9]+)\.([0-9]+)$ ]]; then
            SEMVER="${BASH_REMATCH[1]}"
            echo "**** Semantic version: ${SEMVER} ****"
            echo "Semantic version: ${SEMVER}" >> $GITHUB_STEP_SUMMARY
            echo "semantic_version=${SEMVER}" >> "$GITHUB_OUTPUT"
          else
            echo "**** Can't parse semantic version, exiting ****"
            exit 2
          fi

  frontend:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          sparse-checkout: |
            /patches/*
          sparse-checkout-cone-mode: false

      - name: Check out source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: ${{ github.repository_owner }}/Sonarr
          ref: ${{ needs.prepare.outputs.build_branch }}
          path: build

      - name: Apply patches
        working-directory: build
        run: |
          git apply --stat --apply ../patches/*.patch

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: build/yarn.lock

      - name: Yarn Install
        working-directory: build
        run: yarn install --frozen-lockfile --network-timeout 120000

      - name: Lint
        working-directory: build
        run: yarn lint

      - name: Stylelint
        working-directory: build
        run: yarn stylelint -f github

      - name: Build
        working-directory: build
        run: yarn run build --env production

      - name: Publish UI Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: build_ui
          path: build/_output/UI/**/*
          if-no-files-found: error

  backend:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - linux-musl-arm64
          - linux-musl-x64
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    steps:
      - name: Setup environment variables
        run: |
          echo "SONARR_VERSION=${{ needs.prepare.outputs.version }}" >> "$GITHUB_ENV"

      - name: Check out
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Check out source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: ${{ github.repository_owner }}/Sonarr
          ref: ${{ needs.prepare.outputs.build_branch }}
          path: build

      - name: Apply patches
        working-directory: build
        run: |
          git apply --stat --apply ../patches/*.patch

      - name: Setup dotnet
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: '10.0.x'

      - working-directory: build
        run: dotnet --info

      - name: Build
        working-directory: build
        env:
          BRANCH: develop
        run: |
          ../build.sh --backend -f ${{ needs.prepare.outputs.framework }} -r ${{ matrix.runtime }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: build-${{ matrix.runtime }}
          path: |
            build/_output/*/${{ matrix.runtime }}/publish/*
            build/_output/Sonarr.Update/*/${{ matrix.runtime }}/publish/*
          if-no-files-found: error

  package:
    needs:
      - prepare
      - frontend
      - backend
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - linux-musl-arm64
          - linux-musl-x64
    steps:
      - name: Check out
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Download Artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: build-${{ matrix.runtime }}
          path: _output

      - name: Download UI Artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: build_ui
          path: _output/UI

      - name: Package
        run: |
          ./build.sh --packages -f ${{ needs.prepare.outputs.framework }} -r ${{ matrix.runtime }}
          cp -r _output/UI _artifacts/${{ matrix.runtime }}/${{ needs.prepare.outputs.framework }}/Sonarr
          rm -rf _artifacts/${{ matrix.runtime }}/${{ needs.prepare.outputs.framework }}/Sonarr/Sonarr.Update
          find _artifacts -name "Sonarr" -exec chmod a+x {} \;
          find _artifacts -name "ffprobe" -exec chmod a+x {} \;

      - name: Upload Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: package-${{ matrix.runtime }}
          path: _artifacts/**/*
          if-no-files-found: error

  docker:
    needs:
      - prepare
      - package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup environment variables
        run: |
          echo "BRANCH=${{ needs.prepare.outputs.branch }}" >> "$GITHUB_ENV"
          echo "BRANCH_TO_BUILD=${{ needs.prepare.outputs.build_branch }}" >> "$GITHUB_ENV"
          echo "VERSION=${{ needs.prepare.outputs.version }}" >> "$GITHUB_ENV"
          echo "SEMVER=${{ needs.prepare.outputs.semantic_version }}" >> "$GITHUB_ENV"

      - name: Check out
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Download package artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: package-*
          path: packages
          merge-multiple: true

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/sonarr
          labels: |
            build_version=${{ env.VERSION }}
          tags: |
            type=raw,value=${{ env.BRANCH }}-${{ env.VERSION }},enable=${{ github.event_name != 'pull_request' && (github.ref_name != 'master' && github.ref_name != 'main') && env.BRANCH_TO_BUILD == 'v5-build' }}
            type=raw,value=${{ env.VERSION }},enable=${{ github.event_name != 'pull_request' && (github.ref_name == 'master' || github.ref_name == 'main') && env.BRANCH_TO_BUILD == 'v5-build' }}
            type=raw,value=${{ env.BRANCH }}-${{ env.SEMVER }},enable=${{ github.event_name != 'pull_request' && (github.ref_name != 'master' && github.ref_name != 'main') && env.BRANCH_TO_BUILD == 'v5-build' }}
            type=raw,value=${{ env.SEMVER }},enable=${{ github.event_name != 'pull_request' && (github.ref_name == 'master' || github.ref_name == 'main') && env.BRANCH_TO_BUILD == 'v5-build' }}
            type=raw,value=${{ env.BRANCH }},enable=${{ github.event_name != 'pull_request' && env.BRANCH_TO_BUILD == 'v5-build' }}
            type=raw,value=${{ needs.prepare.outputs.tag_branch }}-${{ env.VERSION }},enable=${{ github.event_name != 'pull_request' && env.BRANCH_TO_BUILD != 'v5-build' }}
            type=raw,value=branch-${{ needs.prepare.outputs.tag_branch }},enable=${{ github.event_name != 'pull_request' && env.BRANCH_TO_BUILD != 'v5-build' }}
            type=ref,event=pr

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
        with:
          platforms: |
            linux/arm64
            linux/amd64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          push: true
          platforms: |
            linux/arm64
            linux/amd64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            VERSION=${{ env.VERSION }}-${{ env.BRANCH }}-r${{ github.run_number }}
            FRAMEWORK=${{ needs.prepare.outputs.framework }}
