name: Delete old container images

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * 1'
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/registry-cleanup.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@d3bdcf5ce9b05f685154e4a16c39233b245e3d53 # v3.1.0
        with:
          account: user
          token: ${{ secrets.GHCR_PAT }}
          image-names: sonarr
          image-tags: "!latest !develop !nightly"
          cut-off: 1w
          keep-n-most-recent: 5
          timestamp-to-use: updated_at
