name: Update package versions
on:
  workflow_run:
    workflows:
      - "Build Docker Image"
    types:
      - "completed"
    branches:
      - "develop"
  pull_request:
    paths:
      - ".github/workflows/versions.yml"
  push:
    branches:
      - "develop"
    paths:
      - ".github/workflows/versions.yml"

jobs:
  versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Update package versions
        uses: docker://ghcr.io/anchore/syft:v1.44.0@sha256:86fde6445b483d902fe011dd9f68c4987dd94e07da1e9edc004e3c2422650de6
        with:
          args: ghcr.io/${{ github.repository_owner }}/sonarr:develop -o table=package_versions.txt

      - name: Commit changes
        if: github.event_name != 'pull_request'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package_versions.txt
          if git diff --staged --quiet; then
            echo "No changes since last run"
          else
            git commit -m "Updating Package Versions"
            git push
          fi
