name: Update package versions
on:
  workflow_run:
    workflows:
      - "Build Docker Image"
    types:
      - "completed"
    branches:
      - "develop"
  pull_request:
    paths:
      - ".github/workflows/versions.yml"
  push:
    branches:
      - "develop"
    paths:
      - ".github/workflows/versions.yml"

jobs:
  versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Update package versions
        uses: docker://ghcr.io/anchore/syft:v1.45.1@sha256:c6d5719f48f5a5986acf2847eb1ed7c53176e712d5721fcd156184cfb262f6eb
        with:
          args: ghcr.io/${{ github.repository_owner }}/sonarr:develop -o table=package_versions.txt

      - name: Commit changes
        if: github.event_name != 'pull_request'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package_versions.txt
          if git diff --staged --quiet; then
            echo "No changes since last run"
          else
            git commit -m "Updating Package Versions"
            git push
          fi
